name: Npm CICD
on: 
  push:
    branches:
      - master

    paths:
      - 'src/**'
      - 'package.json'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'fox-one'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Restore node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '10.23'

    - run: yarn --frozen-lockfile --non-interactive

    - run: yarn build

    - name: Deploy Npm
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./package.json
        tag: 'latest'



