name: Docs CICD
on: 
  push:
    branches:
      - master

    paths:
      - 'src/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'fox-one'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Restore node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '10.23'

    - run: yarn --frozen-lockfile --non-interactive

    - run: yarn build:demo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist-story
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'



